# Generated by Django 5.0.3 on 2024-04-03 11:31

import content.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='专辑名称')),
                ('image', models.FileField(blank=True, null=True, upload_to='album/%Y/%m/%d', validators=[content.models.validate_image_content_type, content.models.validate_image_size])),
                ('artist', models.ManyToManyField(related_name='album_artist', to='content.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='歌曲名称')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.album')),
                ('artist', models.ManyToManyField(related_name='song_artist', to='content.artist')),
            ],
        ),
    ]
