# Generated by Django 5.0.3 on 2024-04-03 14:01

import content.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='songs/%Y/%m/%d', validators=[content.models.validate_song_content_type, content.models.validate_song_size], verbose_name='音频'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='歌单名称')),
                ('image', models.FileField(blank=True, null=True, upload_to='album/%Y/%m/%d', validators=[content.models.validate_image_content_type, content.models.validate_image_size])),
                ('songs', models.ManyToManyField(related_name='playlist_song', to='content.song')),
            ],
        ),
    ]
