# Generated by Django 5.0.3 on 2024-04-03 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_song_audio_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
