# Generated by Django 5.0.3 on 2024-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_playrecord_song_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.PositiveIntegerField(verbose_name='曲序'),
        ),
    ]
