# Generated by Django 5.0.3 on 2024-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_song_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='playrecord',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='播放次数'),
        ),
        migrations.AddField(
            model_name='playrecord',
            name='target_id',
            field=models.UUIDField(default=0, verbose_name='播放内容id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playrecord',
            name='type',
            field=models.CharField(choices=[('PLAYLIST', 'Playlist'), ('ALBUM', 'Album'), ('SONG', 'Song'), ('ARTIST', 'Artist')], default=0, max_length=10, verbose_name='播放内容类型'),
            preserve_default=False,
        ),
    ]
