# Generated by Django 5.0.3 on 2024-04-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_playrecord_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playrecord',
            name='target_id',
            field=models.UUIDField(verbose_name='播放内容id'),
        ),
    ]
