# Generated by Django 5.0.3 on 2024-04-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_playrecord_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
