# Generated by Django 5.0.3 on 2024-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playrecord',
            name='type',
            field=models.CharField(choices=[('PLAYLISTS', 'Playlist'), ('ALBUMS', 'Album'), ('SONGS', 'Song'), ('ARTISTS', 'Artist')], max_length=10, verbose_name='播放内容类型'),
        ),
    ]
